### ISSUE TITLE
[Feature Request] - On deck

### ISSUE THREAD

**Issue by imbaimbaimba** [custom-components/sensor.plex_recently_added#13]
**Describe the solution you'd like**
Would be great, instead of Recently Added, to be able to see what is on deck? That will consequently show me a list of the series I'm watching where a new unwatched episode is available. I would to use that along with recently added for movies.

**Describe alternatives you've considered**
Sorry, I am not smart enough to have thought of anything.

**Additional context**
...

**Comment by 4meuwil** [comment]
This would be great!

**Comment by jer78** [comment]
Would also love this ability!

**Comment by maykar** [comment]
Added in latest release (0.3.3) `on_deck: true`
