### ISSUE TITLE
Platform not found: sensor.plex_recently_added

### ISSUE THREAD

**Issue by topexnative** [custom-components/sensor.plex_recently_added#15]
**Describe the Bug**
Platform not found: sensor.plex_recently_added / sonarr and radarr too

**The Error**
@maykar has my yaml file from previous troubleshooting on upcoming media card issue register

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Yes - @maykar and I have checked the custom card component should be working okay now.  But sensors/components are not showing up.  All the custom components are in www/custom_components/sensor location.  all files have been redownloaded in RAW format to eliminate that issue.

**What data does the sensor display if any?**
No sensor created

**What displays when visiting the API URL from the troubleshooting guide?**
All the correct data from plex/sonarr/radarr - working correctly

**Does the default Home Assistant Plex component work for you?**
Yes - working okay

**Home Assistant Version**
0.87.1

**Additional Context**
sensor.yaml, HA log file and lovelace.yaml file shared with @maykar

**Comment by topexnative** [comment]
@maykar anything here guys?

**Comment by maykar** [comment]
I honestly cannot find anything wrong with your installation from what I've seen. Is your tautulli sensor working properly?

**Comment by maykar** [comment]
Found your issue `config/www/custom_components/sensor` is not where you put components. the custom_components folder belongs in your config directory. `config/custom_components/sensor`

**Comment by topexnative** [comment]
Thanks.  Where did you pick that up from?

________________________________

**Comment by maykar** [comment]
Noticed you said "All the custom components are in www/custom_components/sensor". Or are you asking how did I learn that's where you should put them? I'm sure I saw it in the documentation or on the forums at some point.

**Comment by maykar** [comment]
I'll add that info to the readme when I update next.

**Comment by topexnative** [comment]
Okay thanks - I’ll try when I get home.
