### ISSUE TITLE
Since 0.92, plex_recently_added isn't working

### ISSUE THREAD

**Issue by BRTPOB** [custom-components/sensor.plex_recently_added#19]
There seems to have been a breaking change with 0.92, and since then plex_recently_added doesn't seem to work (along with Sonarr or Radarr). In the logs I see:

    Unable to find services.yaml for the custom_updater integration

I have no idea what should be in services.yaml, and looking at the github page I don't see anything referencing that either. Is this something new that's required, or what do I need to do to get this to work again?

**Comment by maykar** [comment]
That error is for custom_updater and not this component. Make sure for this component you have added the 2 new required files for 0.92.0: [`__init__.py & manifest.json`](https://github.com/custom-components/sensor.plex_recently_added/tree/master/custom_components/plex_recently_added)

**Comment by maykar** [comment]
Looks like the custom_updater error is just a warning at the moment:

https://community.home-assistant.io/t/0-92-heos-somfy-mylink-genius-hub/112980/15
