### ISSUE TITLE
__init__.py causes RunTimeError

### ISSUE THREAD

**Issue by Spankythemusical** [custom-components/sensor.plex_recently_added#20]
**Describe the Bug**
Updated HA to version 92.2.  Plex_Recently_Added, as well as Sonarr_Upcoming_Media, stopped working.  Saw Plex_Recently_Added issue #19, so I added manifest.json and __init__.py to each component folder.  Restarted HA, and the startup would fail.

**The Error**
```
hass[196597]: Traceback (most recent call last):
hass[196597]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
hass[196597]:     callback(self)
hass[196597]:   File "/usr/lib/python3.6/asyncio/futures.py", line 417, in _call_set_state
hass[196597]:     dest_loop.call_soon_threadsafe(_set_state, destination, source)
hass[196597]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 626, in call_soon_threadsafe
hass[196597]:     self._check_closed()
hass[196597]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 366, in _check_closed
hass[196597]:     raise RuntimeError('Event loop is closed')
hass[196597]: RuntimeError: Event loop is closed
```

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?  Yes, yes I did.  These were working before.  If I remove the two new files, HA starts as expected, but without the components.

**Does the default Home Assistant Plex component work for you?**
Yes.

**Home Assistant Version**
0.92.2

**Comment by maykar** [comment]
Are these the only custom components you use? 

Make sure you are using the raw files if copy pasting or download the files from github. `__init.py__` should be an empty file.

**Comment by Spankythemusical** [comment]
I also use custom_updater and feedparser, both of which are operational.  I used whet to download the files into the applicable folder.  I did try to create the files via nano, but the outcome was the same.

**Comment by maykar** [comment]
Odd, I can confirm that both components are operational in 0.92.2. Have you tried deleting the `__pycache__` folder in each components folders if it exists?

**Comment by Spankythemusical** [comment]
Ok, I'm going to go ahead and close this issue.  I completely deleted the folders and started from scratch.  Now they're working the way they were before.  Thank you for your help!
