### ISSUE TITLE
Your configuration contains extra keys that the platform does not support.

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-components/sensor.plex_recently_added#22]
2019-06-06 21:06:43 WARNING (MainThread) [homeassistant.helpers.config_validation] Your configuration contains extra keys that the platform does not support.
Please remove [server].  (See /config/packages/plex_recently_added.yaml, line 5). 
Offending data: {"platform": "plex_recently_added", "token": "<redacted>", "server": "IIIdefconnasIII", "ssl": "<redacted>", "ssl_cert": "<redacted>", "download_images": "<redacted>", "max": "<redacted>", "section_types": "<redacted>"}

**Comment by maykar** [comment]
It's not `server` it's `server_name`
