### ISSUE TITLE
Integration not found when trying to verify its sensor platform

### ISSUE THREAD

**Issue by circa1665** [custom-components/sensor.plex_recently_added#25]
I recently uninstalled the below from hacs and removed from config:

- Plex Recently Added
- Upcoming Media Card

I'm now seeing the following error when I check my config:

```
Configuration invalid
Integration plex_recently_added not found when trying to verify its sensor platform
```

Have been advised to post here instead of in hacs issues, original ticket here: https://github.com/custom-components/hacs/issues/320#issue-470774292

**Comment by maykar** [comment]
Is this still an issue? This component won't load unless it exists somewhere in your configuration.yaml. The error is essentially saying that it is referenced in your configuration, but can't find the file (since you uninstalled).
