### ISSUE TITLE
Images do not show on Google Cast

### ISSUE THREAD

**Issue by jer78** [custom-components/sensor.plex_recently_added#30]
**Describe the Bug**
I can not seem to get the configuration to work to display images when using the Google Cast component. 

**The Error**
No error message

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**

Yes

**What data does the sensor display if any?**

Displays all info minus the pictures (issue on Google Cast only). This works fine on all other browsers

**What displays when visiting the API URL from the troubleshooting guide?**

Displays normally

**Does the default Home Assistant Plex component work for you?**

Yes

**Home Assistant Version**

0.100.3

**Additional Context**

I know this is most likely a Google Cast issue, however, I do have all other images display. 

I tried downloading the images locally by using this configuration:
```
  - platform: plex_recently_added
    token: !secret plex_token
    host: 192.168.1.44
    port: 32400
    #ssl: true
    download_images: true 
    img_dir: '/plex_artwork/'
```

**Comment by maykar** [comment]
I've just updated both this component and Upcoming Media Card to allow for this.
