### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by Tuschz** [custom-components/sensor.plex_recently_added#32]
Hi.

Sample for ui-lovelace.yaml:
    - type: custom:upcoming-media-card
      entity: sensor.plex_recently_added
      title: Recently Downloaded

The entity is called sensor.recently_added

**Comment by maykar** [comment]
I don't know if this was the case in an earlier version, but the sensor's name by default is "sensor.plex_recently_added".

It would only change if you've done so with the `name:` option in the components options.
