### ISSUE TITLE
[Feature Request] Configurable refresh frequency

### ISSUE THREAD

**Issue by chansters** [custom-components/sensor.plex_recently_added#39]
**Is your feature request related to a problem? Please describe.**
The component seems to be refreshing very frequently, maybe every minute? I see this because the images directory seems to be getting cleared out and re-populated very frequently.

**Describe the solution you'd like**
Can you add a configurable option for users to set their own refresh frequency ?

**Comment by maykar** [comment]
If you are using multiple plex sensors this was a bug that was just fixed in the latest release, otherwise it should only update if something has changed/updated.

**Comment by chansters** [comment]
Awesome ! Yes I had two sensors setup and I had the problem with the missing images as well. It does look like the latest update fixed that issue as well as the constant refresh of the images that I saw. Thank you !
