### ISSUE TITLE
Section type Music [Feature Request]

### ISSUE THREAD

**Issue by sepej** [custom-components/sensor.plex_recently_added#41]
Would it be possible to add music for a section type?

**Comment by maykar** [comment]
Will look into this soon. My other Plex project (Plex-Assistant) has a music feature request as well.

I've never used Plex for music so I'll be adding some albums and checking this out.

**Comment by bckthomas** [comment]
Hi
Any news about this ?
Thanks

**Comment by MMachor** [comment]
Was wondering the same.  Any new updates?  Use Plex heavily for music, movies, and TV shows.

**Comment by mkanet** [comment]
The latest versions of this integration allows you to do this.
