### ISSUE TITLE
plex recently added sensor taking too long, throwing errors

### ISSUE THREAD

**Issue by baldfox** [custom-components/sensor.plex_recently_added#42]
**Describe the Bug**
I am getting an error saying the sensor took too long and it's asking me to reach out to the author
**The Error**

Log Details (WARNING)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:297
First occurred: 16:58:45 (2 occurrences)
Last logged: 16:58:50

Updating state for sensor.plex_recently_added (<class 'custom_components.plex_recently_added.sensor.PlexRecentlyAddedSensor'>) took 2.621 seconds. Please report it to the custom component author.
Updating state for sensor.plex_recently_added_2 (<class 'custom_components.plex_recently_added.sensor.PlexRecentlyAddedSensor'>) took 3.920 seconds. Please report it to the custom component author.
Home Assistant has started!

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?
Yes

**What data does the sensor display if any?**
The sensor seems to be working correctly, it's just the errors start to be thrown up again and again

**What displays when visiting the API URL from the troubleshooting guide?**
I get the XML raw data of my library. It all looks ok.

**Does the default Home Assistant Plex component work for you?**
yes

**Home Assistant Version**
0.113

**Additional Context**
N/A

**Comment by maykar** [comment]
Should be fixed in latest release (0.3.3)
