### ISSUE TITLE
Config option to exclude whole libraries [Feature Request]

### ISSUE THREAD

**Issue by jhein05** [custom-components/sensor.plex_recently_added#46]
**Is your feature request related to a problem? Please describe.**
The component displays new items from all libraries of type movies or tv shows, but it would be nice, if you could exclude libraries that contain media, that you don't want to show up in Home Assistant. The "exclude_keyword" option only works on the title of media items, not on library names.

**Describe the solution you'd like**
Add a new config option "exclude_libraries": Allows you to specify a list of library names to be exclude from the sensor if in the title of the library

**Describe alternatives you've considered**
The alternative I am actually using, is to put a keyword into the title of the media items you don't want to show up and then use the "exclude_keywords" option to hide them.

**Comment by crider17** [comment]
+1 for this. Having Libraries defined in Plex as "other videos" showing up for movies. Would love to exclude by library, or even video type.

**Comment by zucram** [comment]
Did anyone solve this? I tried using exclude_keywords: "library name" but that didn't work. Is there any other way to do it?

**Comment by jhein05** [comment]
> Did anyone solve this? I tried using exclude_keywords: "library name" but that didn't work. Is there any other way to do it?

Unfortunately "exclude_keywords" only works for keywords in individual items, not for a whole library. That's why I created this feature request.

**Comment by adizukerman** [comment]
+1 this would be hugely beneficial!

**Comment by zucram** [comment]
@maykar Noticed you updated the addon. Think you can take a look at this issue? Would be greatly appriciated!

**Comment by mkanet** [comment]
This was added in the more recent versions of this integration.
