### ISSUE TITLE
Text shadows

### ISSUE THREAD

**Issue by 18rrs** [custom-components/sensor.plex_recently_added#47]
Thanks for good work on this cards. On my hassio i see a problem on the plex cards that i use. The shadows on the title and info. Not any other integration use shadows on text so this one looks weird, too blurry I have try to edit the upcoming-media-card.js file but with no luck. Even if i try to delete cache and the shadow on text its still there. 
please advice what to modify.

**Comment by maykar** [comment]
This is already a feature of Upcoming Media Card. Check the card's [readme](https://github.com/custom-cards/upcoming-media-card#main-config) for how to disable shadows and other options. Also, issues for the card should be made on the card's github, not here.
