### ISSUE TITLE
No Metadata field for "TV Shows"

### ISSUE THREAD

**Issue by Skaveny** [custom-components/sensor.plex_recently_added#48]
Hello I’m wondering how do I fix this?

Log Details (WARNING)
Logger: custom_components.plex_recently_added.sensor
Source: custom_components/plex_recently_added/sensor.py:273
Integration: plex_recently_added (documentation) 
First occurred: 11:54:25 AM (65 occurrences) 
Last logged: 3:06:25 PM

No Metadata field for "TV Shows"

**Comment by maykar** [comment]
What does your config for the sensor look like? Does the sensor work otherwise, if so what does it show? Do you have shows in your "TV Shows" library?
