### ISSUE TITLE
[Feature request] recently added items on remote server

### ISSUE THREAD

**Issue by Tankdoz** [custom-components/sensor.plex_recently_added#51]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...

I have a connection set up with a remote server of a friend. I would like to be notified if something changes in his server, but the sensor.plex_recently_added component appears to just look at my own movies and series.

**Describe the solution you'd like**
It would be great if Sensor.plex_recently_added would also find the recently added movies/episodes of the remote server

**Describe alternatives you've considered**
I tried to setup additional platform descriptions in my configuration.yaml but in order to connect with the remote server I would need to know the token of the remote server. My friend obviously does not want to share his token as that would make his setup unsecure..

It should be possible to get the recently added information via the connection with my server, as I can see his newly added content in my plex app.

**Additional context**

**Comment by mkanet** [comment]
Sorry for the late reply.  The latest versions of this integration allows you to use multiple instances... so you can monitor multiple plex servers.
