### ISSUE TITLE
[Feature Request] Managed users differences

### ISSUE THREAD

**Issue by DenielTorres** [custom-components/sensor.plex_recently_added#52]
**Is your feature request related to a problem? Please describe.**
Managed users don't get their respective token, so can't add their "progress" of watched and unwatched items. All of their items remain flagged therefore can't use the hide_flagged functionality in the upcoming media card.

**Describe the solution you'd like**
It would be great to separate users and their watch history.

**Describe alternatives you've considered**
An alternative could be to synchronize all managed users' history to an admin.

Thanks in advance for considering my request.

**Comment by mkanet** [comment]
At least for now, not planned.
