### ISSUE TITLE
[Feature Request] Exclude watched from results

### ISSUE THREAD

**Issue by DenielTorres** [custom-components/sensor.plex_recently_added#53]
**Is your feature request related to a problem? Please describe.**
When setting hide_unflagged in the upcoming_media_card component it grabs the first X number of movies and then filters out the watched elements. Causing the list to be always shorter than the set number. Similar functionality has been implemented with the Kodi component. 

**Describe the solution you'd like**
It would be great if this component could already send a differentiator between flagged and not flagged items. Like here: https://github.com/boralyl/kodi-recently-added/issues/4

**Comment by pimp1310** [comment]
any progress here?

**Comment by pimp1310** [comment]
nothing?

**Comment by pimp1310** [comment]
i get it over a second sensor to work, now i only see the unwatched movies

add this template sensor to your configuration.yaml


- platform: template
    sensors:
      plex_unwatched:
        value_template: "{{ states('sensor.plex_recently_added_movies') }}"
        attribute_templates:
          data: "{{ state_attr('sensor.plex_recently_added_movies', 'data') | selectattr('flag', 'defined') | selectattr('flag', 'eq', true) | list }}"


then give the widget the new sensor : sensor.plex_unwatched

and now you only have the unwatched movies in this example.

**Comment by mkanet** [comment]
The latest [official/original Upcoming Media Card](https://github.com/custom-cards/upcoming-media-card) offers the ability to list the watched shows, or filter/sort by any attribute.  You can do this now with any Integration that Upcoming Media Card supports.
