### ISSUE TITLE
[Feature Request] filter on (picture) libraries

### ISSUE THREAD

**Issue by dannymertens** [custom-components/sensor.plex_recently_added#56]
**Is your feature request related to a problem? Please describe.**
Well yes and no, I don't have an option now to show the latest added pictures so problem for me but the sensors works fine for what's defined now ;-)

**Describe the solution you'd like**
I would like to add my picture libraries so that I can see what are the latest pictures added to the plex library

**Describe alternatives you've considered**
I used before the Emby sensor and this had this option, so missing this for the family now

https://github.com/gcorgnet/sensor.emby_upcoming_media

include |   The names or the Emby Libraries you want to include. If not specified, all libraries will be shown and this component will create one sensor per Library

Thanks for considering this!

**Comment by mkanet** [comment]
@dannymertens not sure if you're still watching this issue or not, the latest Plex versions allows you to do this and more via Home Assistant's GUI.
