### ISSUE TITLE
plex_recently_added: Error on device update!

### ISSUE THREAD

**Issue by greghesp** [custom-components/sensor.plex_recently_added#57]
**Describe the Bug**
Unable to use sensor

**The Error**
```
Logger: homeassistant.components.sensor
Source: custom_components/plex_recently_added/sensor.py:269
Integration: Sensor (documentation, issues)
First occurred: 12:55:46 (1 occurrences)
Last logged: 12:55:46

plex_recently_added: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/config/custom_components/plex_recently_added/sensor.py", line 269, in async_update
    sub_sec = json.loads(sub_sec)
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Plex recently added URL shows XML of recently added

**What data does the sensor display if any?**
Does not show

**What displays when visiting the API URL from the troubleshooting guide?**
XML Media Container with all recently added plex information. Snippet below
![image](https://user-images.githubusercontent.com/768908/117294826-009db000-ae6b-11eb-9ca1-a461cd0bd93f.png)

**Does the default Home Assistant Plex component work for you?**
Yes

**Home Assistant Version**
core-2021.5.0

**Comment by jhockert** [comment]
Exactly the same error here. Using postman I am able to get json formatting

**Comment by mkanet** [comment]
guys, please try the completely rewritten version of this integration that can be configured in the Home Assistant GUI.
