### ISSUE TITLE
[Feature Request] Should be able to get only unwatched items

### ISSUE THREAD

**Issue by tmcarr** [custom-components/sensor.plex_recently_added#6]
It would be nice to be able to configure this sensor to only show unwatched items. 

I'll be glad to hack this out, I just wanted to make sure I threw a todo in. I dont think it should be terribly hard.

**Comment by maykar** [comment]
Be mindful of max items. If we ignore watched items it needs to be filtered before `self.max_items` is used when grabbing the json. We could also just rework how to limit to max_items, as long as we aren't downloading more images than needed.

**Comment by maykar** [comment]
This functionality was added to the card with features to hide flagged items or only show flagged items

**Comment by DenielTorres** [comment]
Hi there! I seem to have issues with this functionality. I have hide_unflagged: true in my config and the sensor still shows items that are unflagged from Plex. Is there any setting I have to do on Plax's side? Thanks in advance!

**Comment by maykar** [comment]
Try not to post issues or requests on closed issues, make a new one instead.

The sensor will show all items and doesn't have an option to exclude watched yet, but feel free to make a feature request for it. Right now, the card handles the filtering of items that the sensor provides.

Unless of course you're saying that the card is displaying unflagged items even with the setting, then of course that would be an issue you should post to the cards github page.
