### ISSUE TITLE
`device_state_attributes` property replaced with `extra_state_attributes` in HA core

### ISSUE THREAD

**Issue by firstof9** [custom-components/sensor.plex_recently_added#60]
**Describe the Bug**
The `device_state_attributes` property has been replaced with `extra_state_attributes` in HA core.

**The Error**
```
(<class 'custom_components.plex_recently_added.sensor.PlexRecentlyAddedSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Start HA

**What data does the sensor display if any?**
n/a

**What displays when visiting the API URL from the troubleshooting guide?**
n/a

**Does the default Home Assistant Plex component work for you?**
n/a

**Home Assistant Version**
2021.12.0b1

**Additional Context**
n/a

**Comment by mkanet** [comment]
Please try the newer version of this Integration. A lot has changed since then.  Sorry for the delay.
