### ISSUE TITLE
[Feature Request] $date is in US format, makes it hard for people in the rest of the world to read

### ISSUE THREAD

**Issue by 1liminal1** [custom-components/sensor.plex_recently_added#61]
**Is your feature request related to a problem? Please describe.**
$date is in US format, makes it hard for people in the rest of the world to read

**Describe the solution you'd like**
Have an option for DDMM something like "$datedm"

**Describe alternatives you've considered**
If there is another way to display this, would be happy?

**Additional context**
I think thats all, pretty simple stuff :)

**Comment by maykar** [comment]
Upcoming media card has a config option for changing the date format

**Comment by 1liminal1** [comment]
Ok thanks, 

But there seems to be no information on how this change is made?
