### ISSUE TITLE
Not pulling in upcoming events

### ISSUE THREAD

**Issue by jsp196** [custom-components/sensor.plex_recently_added#63]
**Describe the Bug**
Component is not retrieving data from my Plex server

**The Error**
The only related error is:
` Logger: homeassistant.helpers.entity
Source: helpers/entity.py:694
First occurred: 5:46:14 PM (2 occurrences)
Last logged: 5:46:14 PM

    Update of sensor.plex_recently_added_tv is taking over 10 seconds
    Update of sensor.plex_recently_added is taking over 10 seconds
`

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Followed all those directions and I do see XML data when I enter the URL + key provided.  For some reason, on my desktop PC it displays the XML info even with ?X-Plex-Token= left empty.  The Home Assistant box is on the same network / same subnet.

Also tried the following:
Removed Component and sensors
Rebooted
Added component 
Rebooted
Added sensors
Rebooted
Also attempted to remove then install a previous version of the component also to no avail.

**What data does the sensor display if any?**
Shows online with the following data (no idea why the following block won't show up as code):

`data:
  - title_default: $title
    line1_default: $episode
    line2_default: $release
    line3_default: $number - $rating - $runtime
    line4_default: $genres
    icon: mdi:eye-off
friendly_name: Plex Recently Added`

When I attempted to use other ways to access my server (FQDN, .local address) they showed "unable to connect" so it seems like it's making an effort with the IP and Port.

**What displays when visiting the API URL from the troubleshooting guide?**
Repeated for several shows, then a section about movies, etc.

`<MediaContainer size="50" allowSync="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1628745015" mixedParents="1">
<Directory allowSync="1" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="b0b1ed34-1b1a-45eb-9e5e-4fc3a2a58e68" ratingKey="24510" key="/library/metadata/24510/children" parentRatingKey="24509" guid="plex://season/60f6886cfc1a24002d4a4ed5" parentGuid="plex://show/#################" `

**Does the default Home Assistant Plex component work for you?**
Was unable to get this to work - it connected but then the sensor that I updated to the information for my HASS installation didn't load, but the other two still did.

**Home Assistant Version**
2021.12.9

**Additional Context**
Have been at this for a long time - it worked for a while and then just suddenly stopped working.  I verified the Plex key wasn't the issue.

**Comment by mkanet** [comment]
Please try the latest versions of this integration, it allows you to use pictures, music, etc.
