### ISSUE TITLE
getting untested by HA error

### ISSUE THREAD

**Issue by andreasc1** [custom-components/sensor.plex_recently_added#64]
hi, we are getting this error all over the logs:

`2022-02-17 09:24:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration plex_recently_added which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

any idea to avoid this error?

**Comment by mkanet** [comment]
No.  This is a normal message that Home Assistant will display for HACS integrations.
