### ISSUE TITLE
[Feature Request] Watched flag seems not to reflect Managed users

### ISSUE THREAD

**Issue by jef74** [custom-components/sensor.plex_recently_added#84]
**Is your feature request related to a problem? Please describe.**
The watched flag seems only to reflect Plex admin account, even if I define User when configure the addon.

**Describe the solution you'd like**
The addon should reflect a defined users watched flag. In my case I'm talking of Managed users under Plex home.

**Describe alternatives you've considered**

**Additional context**

**Comment by mkanet** [comment]
I don't think the Plex API supports this. Similar limitation to why managed users can't `Add to watchlist` for `Discover` section in Plex.
